// MAC OS SIDE LAYOUT

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import FinderBarComponent from "@/components/macOs-linux/FinderBarComponent";
import ApplicationBarComponent from "@/components/macOs-linux/ApplicationsBarComponent"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <header>
            <FinderBarComponent/>
        </header>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      
      >
        {children}
      </body>
      <footer>
        <ApplicationBarComponent/>
      </footer>
    </html>
  );
}
